// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU_sfsObpSqQP4yfWRLf65FzeRKPFbSqM',
    appId: '1:692305265604:web:69b04fc2460c7eb67c9a91',
    messagingSenderId: '692305265604',
    projectId: 'myfit-5a063',
    authDomain: 'myfit-5a063.firebaseapp.com',
    storageBucket: 'myfit-5a063.appspot.com',
    measurementId: 'G-4G4C3PJ54P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZbaqSscDDLwrKfhGhw7TyTqZ_Ro4_sE',
    appId: '1:692305265604:android:7e13098384ec0f8d7c9a91',
    messagingSenderId: '692305265604',
    projectId: 'myfit-5a063',
    storageBucket: 'myfit-5a063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM92bEvonHZ_9oisgnXnnpAt1HgebZOYc',
    appId: '1:692305265604:ios:3d10a5f7a75ad7c77c9a91',
    messagingSenderId: '692305265604',
    projectId: 'myfit-5a063',
    storageBucket: 'myfit-5a063.appspot.com',
    iosBundleId: 'com.example.myfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM92bEvonHZ_9oisgnXnnpAt1HgebZOYc',
    appId: '1:692305265604:ios:3d10a5f7a75ad7c77c9a91',
    messagingSenderId: '692305265604',
    projectId: 'myfit-5a063',
    storageBucket: 'myfit-5a063.appspot.com',
    iosBundleId: 'com.example.myfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU_sfsObpSqQP4yfWRLf65FzeRKPFbSqM',
    appId: '1:692305265604:web:a1391e6bade247907c9a91',
    messagingSenderId: '692305265604',
    projectId: 'myfit-5a063',
    authDomain: 'myfit-5a063.firebaseapp.com',
    storageBucket: 'myfit-5a063.appspot.com',
    measurementId: 'G-PV495WYNQH',
  );
}
